In [1]:
import numpy as np
import time

a = np.array([[1,2,3]])
b = np.array([[4],[5],[6]])
print("a: "+ str(a))
print("b: "+ str(b))
#Broadcasting
c = a*b
print("Broadcasting, a*b: "+str(c))
#Dot operation on 1D vectors, it is vector multiplication
c = np.dot(a,b)
print("Dot operation, dot(a,b): "+str(c))


a: [[1 2 3]]
b: [[4]
 [5]
 [6]]
Broadcasting, a*b: [[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
Dot operation, dot(a,b): [[32]]


In [2]:
#dot operation on 2D arrays, it is matrix multiplication
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[0,1],[2,3],[4,5]])
print("a: "+ str(a))
print("b: "+ str(b))
c = np.dot(a,b)
print("c: "+ str(c))

a: [[1 2 3]
 [4 5 6]]
b: [[0 1]
 [2 3]
 [4 5]]
c: [[16 22]
 [34 49]]


In [3]:
#Don't use (n,)shaped rank 1 arrat, it can confuse you because it is neither column nor row vector
#Try to be sure about the shape of your arrays by using assert and reshape
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorization takes "+ str((toc - tic)*1000)+ " ms")

tic = time.time()
c = 0
for i in range(1000000):
    c+=a[i]*b[i]

toc = time.time()
print(c)
print("Non-vectorization, for loop opt, takes "+str(1000*(toc-tic)) +" ms")


249832.132283403
Vectorization takes 7.014751434326172 ms
249832.13228340453
Non-vectorization, for loop opt, takes 608.8016033172607 ms


In [4]:
#Broadcasting & assertion
a = np.array([[1,2,3],[4,5,6]])
b = a + np.array([[1,1,1]])
print(b)
c = a + 5
print(c)
assert(c.shape == (2,3))
d = c.sum(axis=0)
print(d)
e = c/d
print(100*e)

[[2 3 4]
 [5 6 7]]
[[ 6  7  8]
 [ 9 10 11]]
[15 17 19]
[[40.         41.17647059 42.10526316]
 [60.         58.82352941 57.89473684]]


In [12]:
#3D Arrays
a = np.array([[[1,2,3],[5,6,7]], [[3,4,5],[0,1,2]],[[1,2,3],[5,6,7]], [[3,4,5],[0,1,2]]])
print("a: "+str(a))
print("shape of a: " + str(np.shape(a)))

a: [[[1 2 3]
  [5 6 7]]

 [[3 4 5]
  [0 1 2]]

 [[1 2 3]
  [5 6 7]]

 [[3 4 5]
  [0 1 2]]]
shape of a: (4, 2, 3)
